### PR TITLE
Update 1.6.0

### PR DESCRIPTION
**Pull request by Genetik57**
*Compilation with Kernel 4.15 and above fixed
*Compatibility with RPI4 added
*Find the BCM peripherals base address dynamically
*Hotkey buttons added

Based on the work of @cmitu

Signed-off-by: Jérémy Del Grosso genetik57@batocera.org

### CODE REVIEW

**Comment by cmitu** [comment]
Note that the Pi4 support might not work - we had a couple of users in the RetroPie forum that reported it doesn't fully work. Since I don't have a GPIO set-up right now to test the driver, I can't confirm it.

**Comment by Genetik57** [comment]
Hi @cmitu how are you?

I will test this for you as soon as Batocera is compatible :)

Your update works perfectly thank you very much for your work

**Comment by cmitu** [comment]
@Genetik57 If you have such a setup to test, it would be good to have a confirmation (or not) if it's working or not.

**Comment by Genetik57** [comment]
@cmitu I can soon as possible

**Comment by cmitu** [comment]
There's no rush, thank you for offering to test it.

**Comment by Genetik57** [comment]
It is always interesting to exchange our results with other retro gaming projects

**Pull request merged**
